# Generated by Django 3.2.8 on 2021-10-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresults',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
