# Generated by Django 3.2.8 on 2021-11-01 07:38

from django.db import migrations
import exams.models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_examresults_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresults',
            name='taken_on',
            field=exams.models.CustomDateTimeField(auto_now_add=True, unique=True),
        ),
    ]
