# Generated by Django 3.2.8 on 2021-11-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_examresults_taken_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_one_correct_answer',
            field=models.BooleanField(default=False),
        ),
    ]
