# Generated by Django 3.2.8 on 2021-11-08 12:54

from django.db import migrations, models
import exams.models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_question_has_one_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_user_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='source',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='examresults',
            name='taken_on',
            field=exams.models.CustomDateTimeField(unique=True),
        ),
    ]
