# Generated by Django 3.2.8 on 2021-11-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20211108_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='uploader',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
