# Generated by Django 3.2.8 on 2021-11-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_exam_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='is_user_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='uploader',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
