# Generated by Django 3.2.8 on 2021-11-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_auto_20211111_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
