# Generated by Django 3.2.8 on 2021-11-13 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import exams.models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_alter_exam_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_on', exams.models.CustomDateTimeField(unique=True)),
                ('text', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exams.question')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
