# Generated by Django 3.2.8 on 2021-11-14 11:31

from django.db import migrations
import exams.models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_questionreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionreport',
            name='reported_on',
            field=exams.models.CustomDateTimeField(auto_now_add=True, unique=True),
        ),
    ]
