# Generated by Django 3.2.8 on 2021-11-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_alter_questionreport_reported_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionreport',
            name='is_resolved',
        ),
        migrations.AddField(
            model_name='questionreport',
            name='status',
            field=models.CharField(choices=[('N', 'new'), ('A', 'accepted'), ('R', 'rejected')], default='N', max_length=1),
        ),
    ]
