# Generated by Django 3.2.8 on 2021-11-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_auto_20211114_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionreport',
            name='resolution',
            field=models.TextField(default=''),
        ),
    ]
