# Generated by Django 3.2.8 on 2021-11-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_questionreport_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='is_app_admin',
            field=models.BooleanField(default=False),
        ),
    ]
